<?php

declare(strict_types=1);

namespace Mentor\NodeVisitor;

use PhpParser\Node;
use PhpParser\NodeVisitorAbstract;

final class MinimalVersionNodeVisitor extends NodeVisitorAbstract
{
    public function enterNode(Node $node)
    {
        // nodee to PHP version
        // [] → 5.4
        // traitj → 5.4
        // match → php 8
        // etc.
        // @todo test
        return parent::enterNode($node); // TODO: Change the autogenerated stub
    }
}